//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailDispatcher.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassesDetail
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_Usmjerenje { get; set; }
        public System.Guid ID_Class { get; set; }
        public System.DateTime Datum { get; set; }
        public bool Status { get; set; }
        public Nullable<System.Guid> ID_version { get; set; }
        public Nullable<System.Guid> ID_Razrednik { get; set; }
        public Nullable<System.Guid> ID_ZamjenikRazrednika { get; set; }
    }
}
