//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailDispatcher.Entity
{
    using System;
    
    public partial class CMbyID_Result4
    {
        public Nullable<System.Guid> ID { get; set; }
        public string Name { get; set; }
        public string Razred { get; set; }
        public string Sat { get; set; }
        public string SubjectsEx { get; set; }
        public string ProfCM { get; set; }
        public string SubjectsCm { get; set; }
        public string Kabinet { get; set; }
        public System.Guid ID_Period { get; set; }
        public string Short { get; set; }
        public System.Guid IDClass { get; set; }
        public System.Guid IDSubject { get; set; }
        public System.Guid IDSubjecEx { get; set; }
        public Nullable<System.Guid> TeachersIDCM { get; set; }
        public System.Guid ID_Classrom { get; set; }
        public System.Guid IDCMdetail { get; set; }
        public Nullable<bool> Pay { get; set; }
        public Nullable<System.Guid> ID_StatusCM { get; set; }
        public string Poruka { get; set; }
        public Nullable<int> Mail { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public System.Guid ID_TeachersCM { get; set; }
    }
}
