//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailDispatcher.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectDetail
    {
        public System.Guid ID { get; set; }
        public Nullable<int> Norma { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> Nastava { get; set; }
        public Nullable<int> Vjezbe { get; set; }
        public Nullable<System.Guid> ID_Usmjerenje { get; set; }
        public Nullable<System.Guid> ID_Subject { get; set; }
    }
}
