//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailDispatcher.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string color { get; set; }
        public System.Guid ID { get; set; }
        public int Status { get; set; }
        public Nullable<System.Guid> ID_Teacherq { get; set; }
        public Nullable<bool> Razrednik { get; set; }
    }
}
