//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailDispatcher.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dBTeslaEntities : DbContext
    {
        public dBTeslaEntities()
            : base("name=dBTeslaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChangeManagementDetail> ChangeManagementDetail { get; set; }
        public virtual DbSet<ChangeManagementMaster> ChangeManagementMaster { get; set; }
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<ClassesDetail> ClassesDetail { get; set; }
        public virtual DbSet<Classrooms> Classrooms { get; set; }
        public virtual DbSet<ClassroomsQ> ClassroomsQ { get; set; }
        public virtual DbSet<ClassSubjects> ClassSubjects { get; set; }
        public virtual DbSet<Ostalazaduzenja> Ostalazaduzenja { get; set; }
        public virtual DbSet<Periods> Periods { get; set; }
        public virtual DbSet<PredmetiUsmjerenja> PredmetiUsmjerenja { get; set; }
        public virtual DbSet<Smjerovi> Smjerovi { get; set; }
        public virtual DbSet<SubjectDetail> SubjectDetail { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<TeacherQ> TeacherQ { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<TeacherSubjects> TeacherSubjects { get; set; }
        public virtual DbSet<Turnusi> Turnusi { get; set; }
        public virtual DbSet<Usmjerenja> Usmjerenja { get; set; }
        public virtual DbSet<UsmjerenjeRazred> UsmjerenjeRazred { get; set; }
        public virtual DbSet<VrstaPredmeta> VrstaPredmeta { get; set; }
        public virtual DbSet<VrstaRO> VrstaRO { get; set; }
        public virtual DbSet<Zvanje> Zvanje { get; set; }
    
        public virtual ObjectResult<CMbyID_Result4> CMbyID(string parentGuid)
        {
            var parentGuidParameter = parentGuid != null ?
                new ObjectParameter("ParentGuid", parentGuid) :
                new ObjectParameter("ParentGuid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CMbyID_Result4>("CMbyID", parentGuidParameter);
        }
    
        public virtual ObjectResult<CMDeatailbyID_Result> CMDeatailbyID(string parentGuid)
        {
            var parentGuidParameter = parentGuid != null ?
                new ObjectParameter("ParentGuid", parentGuid) :
                new ObjectParameter("ParentGuid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CMDeatailbyID_Result>("CMDeatailbyID", parentGuidParameter);
        }
    
        public virtual ObjectResult<CMbyIDMD_Result> CMbyIDMD(string parentGuid)
        {
            var parentGuidParameter = parentGuid != null ?
                new ObjectParameter("ParentGuid", parentGuid) :
                new ObjectParameter("ParentGuid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CMbyIDMD_Result>("CMbyIDMD", parentGuidParameter);
        }
    
        public virtual ObjectResult<CMbyIDTch_Result> CMbyIDTch(string parentGuid, string parentGuidTCH)
        {
            var parentGuidParameter = parentGuid != null ?
                new ObjectParameter("ParentGuid", parentGuid) :
                new ObjectParameter("ParentGuid", typeof(string));
    
            var parentGuidTCHParameter = parentGuidTCH != null ?
                new ObjectParameter("ParentGuidTCH", parentGuidTCH) :
                new ObjectParameter("ParentGuidTCH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CMbyIDTch_Result>("CMbyIDTch", parentGuidParameter, parentGuidTCHParameter);
        }
    }
}
