//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailDispatcher.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VrstaPredmeta
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Kratica { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    }
}
